package com.dm.cms.sqldao;

import com.dm.cms.model.CmsAttachment;

public interface CmsAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_attachment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_attachment
     *
     * @mbggenerated
     */
    int insert(CmsAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_attachment
     *
     * @mbggenerated
     */
    int insertSelective(CmsAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_attachment
     *
     * @mbggenerated
     */
    CmsAttachment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_attachment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CmsAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_attachment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CmsAttachment record);
}