package com.dm.cms.sqldao;

import com.dm.cms.model.CmsAttachment;
import com.dm.cms.model.CmsCheck;
import com.dm.cms.model.CmsContent;

import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface CmsContentMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cms_content
	 * 
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cms_content
	 * 
	 * @mbggenerated
	 */
	int insert(CmsContent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cms_content
	 * 
	 * @mbggenerated
	 */
	int insertSelective(CmsContent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cms_content
	 * 
	 * @mbggenerated
	 */
	CmsContent selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cms_content
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(CmsContent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cms_content
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(CmsContent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cms_content
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CmsContent record);

	List<CmsContent> selectRecordByArgMap(Map argMap);

	/**
	 * for 一键静态化
	 * 
	 * @param argMap
	 * @return
	 */
	List<CmsContent> selectRecordByPage(Map argMap);

	CmsContent selectByParams(Map argMap);

	int insertAttachment(@Param(value = "contentId") Integer contentId,
			@Param(value = "attachmentId") Integer attachmentId);

	int deleteAttachment(@Param(value = "contentId") Integer contentId);

	List<CmsAttachment> selectAttachementByCmsContentId(
			@Param(value = "contentId") Integer contentId);

	String selectAttachmentIdsByCMsContentId(
			@Param(value = "contentId") Integer contentId);

	List<CmsContent> selectByChannelIds(Map map);

	int selectCount(@Param(value = "channelIds") List<Integer> channelIds);

	String selectContentIdsByAttachmentId(Integer id);

	List<CmsContent> selectTopOne();
	List<CmsContent> selectIsPictures();
	
	List<CmsCheck> selectViewByReord(Map map);
	List<CmsContent> selectByLeaderId(String leaderId);

}
