package com.dm.cms.sqldao;

import com.dm.cms.model.CmsTemplate;

import java.util.List;
import java.util.Map;

public interface CmsTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_template
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_template
     *
     * @mbggenerated
     */
    int insert(CmsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_template
     *
     * @mbggenerated
     */
    int insertSelective(CmsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_template
     *
     * @mbggenerated
     */
    CmsTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CmsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CmsTemplate record);

    List<CmsTemplate> selectRecordsByArgMap(Map argMap);
}
