package com.dm.cms.sqldao;

import com.dm.cms.model.CmsTemplateBlob;

public interface CmsTemplateBlobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_template_blob
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_template_blob
     *
     * @mbggenerated
     */
    int insert(CmsTemplateBlob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_template_blob
     *
     * @mbggenerated
     */
    int insertSelective(CmsTemplateBlob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_template_blob
     *
     * @mbggenerated
     */
    CmsTemplateBlob selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_template_blob
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CmsTemplateBlob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_template_blob
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(CmsTemplateBlob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_template_blob
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CmsTemplateBlob record);
}