package com.dm.cms.model;

import java.io.Serializable;
import java.util.Date;

public class CmsAttachment implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_attachment.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_attachment.attachment_type
     *
     * @mbggenerated
     */
    private Short attachmentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_attachment.attachment_name
     *
     * @mbggenerated
     */
    private String attachmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_attachment.attachment_url
     *
     * @mbggenerated
     */
    private String attachmentUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_attachment.file_size
     *
     * @mbggenerated
     */
    private Long fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_attachment.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_attachment.create_user
     *
     * @mbggenerated
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_attachment.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_attachment.is_active
     *
     * @mbggenerated
     */
    private Boolean isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_attachment
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_attachment.id
     *
     * @return the value of cms_attachment.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_attachment.id
     *
     * @param id the value for cms_attachment.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_attachment.attachment_type
     *
     * @return the value of cms_attachment.attachment_type
     * @mbggenerated
     */
    public Short getAttachmentType() {
        return attachmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_attachment.attachment_type
     *
     * @param attachmentType the value for cms_attachment.attachment_type
     * @mbggenerated
     */
    public void setAttachmentType(Short attachmentType) {
        this.attachmentType = attachmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_attachment.attachment_name
     *
     * @return the value of cms_attachment.attachment_name
     * @mbggenerated
     */
    public String getAttachmentName() {
        return attachmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_attachment.attachment_name
     *
     * @param attachmentName the value for cms_attachment.attachment_name
     * @mbggenerated
     */
    public void setAttachmentName(String attachmentName) {
        this.attachmentName = attachmentName == null ? null : attachmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_attachment.attachment_url
     *
     * @return the value of cms_attachment.attachment_url
     * @mbggenerated
     */
    public String getAttachmentUrl() {
        return attachmentUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_attachment.attachment_url
     *
     * @param attachmentUrl the value for cms_attachment.attachment_url
     * @mbggenerated
     */
    public void setAttachmentUrl(String attachmentUrl) {
        this.attachmentUrl = attachmentUrl == null ? null : attachmentUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_attachment.file_size
     *
     * @return the value of cms_attachment.file_size
     * @mbggenerated
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_attachment.file_size
     *
     * @param fileSize the value for cms_attachment.file_size
     * @mbggenerated
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_attachment.create_time
     *
     * @return the value of cms_attachment.create_time
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_attachment.create_time
     *
     * @param createTime the value for cms_attachment.create_time
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_attachment.create_user
     *
     * @return the value of cms_attachment.create_user
     * @mbggenerated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_attachment.create_user
     *
     * @param createUser the value for cms_attachment.create_user
     * @mbggenerated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_attachment.update_time
     *
     * @return the value of cms_attachment.update_time
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_attachment.update_time
     *
     * @param updateTime the value for cms_attachment.update_time
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_attachment.is_active
     *
     * @return the value of cms_attachment.is_active
     * @mbggenerated
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_attachment.is_active
     *
     * @param isActive the value for cms_attachment.is_active
     * @mbggenerated
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    public String getRealName() {
        return attachmentUrl.substring(attachmentUrl.lastIndexOf("/"));
    }
}
