package com.dm.cms.model;

import java.io.Serializable;
import java.util.Date;

public class CmsTemplate implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_template.id
     *
     * @mbggenerated
     */
    private Integer id;
    private String templateType;
    private Integer siteId;
    private String siteName;

    public String getTemplateType() {
		return templateType;
	}

	public void setTemplateType(String templateType) {
		this.templateType = templateType;
	}

	public Integer getSiteId() {
		return siteId;
	}

	public void setSiteId(Integer siteId) {
		this.siteId = siteId;
	}
	
	public String getSiteName() {
		return siteName;
	}

	public void setSiteName(String siteName) {
		this.siteName = siteName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_template.template_name
     *
     * @mbggenerated
     */
    private String templateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_template.template_path
     *
     * @mbggenerated
     */
    private String templatePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_template.template_blob_id
     *
     * @mbggenerated
     */
    private Integer templateBlobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_template.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_template.create_user
     *
     * @mbggenerated
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_template.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_template
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_template.id
     *
     * @return the value of cms_template.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_template.id
     *
     * @param id the value for cms_template.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_template.template_name
     *
     * @return the value of cms_template.template_name
     *
     * @mbggenerated
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_template.template_name
     *
     * @param templateName the value for cms_template.template_name
     *
     * @mbggenerated
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName == null ? null : templateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_template.template_path
     *
     * @return the value of cms_template.template_path
     *
     * @mbggenerated
     */
    public String getTemplatePath() {
        return templatePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_template.template_path
     *
     * @param templatePath the value for cms_template.template_path
     *
     * @mbggenerated
     */
    public void setTemplatePath(String templatePath) {
        this.templatePath = templatePath == null ? null : templatePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_template.template_blob_id
     *
     * @return the value of cms_template.template_blob_id
     *
     * @mbggenerated
     */
    public Integer getTemplateBlobId() {
        return templateBlobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_template.template_blob_id
     *
     * @param templateBlobId the value for cms_template.template_blob_id
     *
     * @mbggenerated
     */
    public void setTemplateBlobId(Integer templateBlobId) {
        this.templateBlobId = templateBlobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_template.create_time
     *
     * @return the value of cms_template.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_template.create_time
     *
     * @param createTime the value for cms_template.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_template.create_user
     *
     * @return the value of cms_template.create_user
     *
     * @mbggenerated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_template.create_user
     *
     * @param createUser the value for cms_template.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_template.update_time
     *
     * @return the value of cms_template.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_template.update_time
     *
     * @param updateTime the value for cms_template.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}