package com.dm.cms.model;

import java.io.Serializable;
import java.util.Date;

public class CmsTemplateBlob implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_template_blob.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_template_blob.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_template_blob.create_user
     *
     * @mbggenerated
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_template_blob.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_template_blob.template_blob
     *
     * @mbggenerated
     */
    private byte[] templateBlob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_template_blob
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_template_blob.id
     *
     * @return the value of cms_template_blob.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_template_blob.id
     *
     * @param id the value for cms_template_blob.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_template_blob.create_time
     *
     * @return the value of cms_template_blob.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_template_blob.create_time
     *
     * @param createTime the value for cms_template_blob.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_template_blob.create_user
     *
     * @return the value of cms_template_blob.create_user
     *
     * @mbggenerated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_template_blob.create_user
     *
     * @param createUser the value for cms_template_blob.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_template_blob.update_time
     *
     * @return the value of cms_template_blob.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_template_blob.update_time
     *
     * @param updateTime the value for cms_template_blob.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_template_blob.template_blob
     *
     * @return the value of cms_template_blob.template_blob
     *
     * @mbggenerated
     */
    public byte[] getTemplateBlob() {
        return templateBlob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_template_blob.template_blob
     *
     * @param templateBlob the value for cms_template_blob.template_blob
     *
     * @mbggenerated
     */
    public void setTemplateBlob(byte[] templateBlob) {
        this.templateBlob = templateBlob;
    }
}